### ISSUE TITLE
Deployment Instructions

### ISSUE THREAD

**Issue by latetedemelon** [msembinelli/questrade-google-apps-script#1]
I've created the request files in google sheets but I'm having some execution issues with the script.  Are you able to possible provide some high level deployment instructions for the code.

**Comment by darthcloud** [comment]
@rmclellan @msembinelli doGet function hint that this might need to be deploy as a webapps but when doing so I get error:

Cannot call SpreadsheetApp.getUi() from this context. (line 169, file "Questrade")

Instruction would help!

**Comment by msembinelli** [comment]
I built this script a long time ago and have since made changes I haven't committed yet. I also did some more modern methods with some other scripts recently (using clasp) that lets you deploy this easier. I will try to get my changes posted up. There is also no need for ssdb anymore since you can use script/user properties to store the refresh key.

**Comment by msembinelli** [comment]
Pushed new code up in bc5d9639a1a3a09d13facd26cdabac27ea10cabe

Please try it out. Just remember I wrote this for a very specific scenario for my spreadsheet. So it may not work perfectly for you, but you can modify as you see fit.

**Comment by darthcloud** [comment]
Thank! @msembinelli will give it a try!

**Comment by msembinelli** [comment]
I forgot to mention, instructions are in the README :)

**Comment by darthcloud** [comment]
Followed instruction created empty spreadsheet, uploaded scripts with clasp, and added Script Properties. Finally added a menu button to launch run function:

function onOpen(e) {
  SpreadsheetApp.getUi()
      .createMenu('Questrade')
      .addItem('Run', 'run')
      .addToUi();
}

Now clicking run I do get the prompt for my QT refresh token, then after pasting it I get the prompt again right away. I guess an error occurred, anyway to retrieve what the error was? Sorry not very familiar with Google Apps scripts yet!

Thanks for taking time to upload new version, very appreciated!

**Comment by darthcloud** [comment]
Got it to access my token after refresh. Added sheet Positions and Balances now I get the header in positions sheet but no data. Figured how to see the debug log. I see the script get my account data poperly.

I got this error however Exception: Those rows are out of bounds. Trying to see where it come from!

**Comment by msembinelli** [comment]
Hey @darthcloud 

It's quite possible that the issue lies with the writeJSONToSheet function:
```
    // We want to erase everything below the headers so that we get new data
    sheet.deleteRows(2, sheet.getLastRow() - 1);
```
The above line can be problematic if the sheet doesn't have some empty rows. You may get out of bounds errors if there is only 1, or 2 rows in the sheet.

What does the positions sheet look like for you?

EDIT: I should also say that this code could be greatly improved upon, so if you solve any issues, feel free to create a PR

**Comment by darthcloud** [comment]
Ok got it working! I wrote something far in the bottom right corner of both sheet and it resolved the out of bound issues.

Thanks a lot for sharing this code it's really useful. Will share any change I do through PR or fork if too radical ;)

**Comment by ghost** [comment]
Awesome to hear @darthcloud ! Excited to see what you can do with it!
